[workspace]
members = [".", "benches"]

[package]
name = "imprint"
version = "0.1.0"
edition = "2024"
description = "A binary row serialization format for data pipelines"
license = "MIT"

[dependencies]
thiserror = "1.0"
bytes = "1.5"
prost-build = "0.13.5"

[dev-dependencies]
proptest = "1.4"
